version: "3.8"

services:
  ui:
    build:
      context: ./apps/ui
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/ui:/app
      - /app/node_modules

  server:
    build:
      context: ./apps/server
      dockerfile: docker/Dockerfile
    volumes:
      - ./apps/server:/code
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: l3-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
