version: "3.8"

services:
  ui:
    build:
      context: ./apps/ui
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/ui:/app
      - /app/node_modules

  server:
    build:
      context: ./apps/server
      dockerfile: docker/Dockerfile
    volumes:
      - ./apps/server:/code
    ports:
      - "4000:4000"
